all:
  children:
    purefa:
      hosts:
        purefa1:
          http_port: 443
          ansible_host: purefa1.lab.local
        purefa2:
          http_port: 444
          ansible_host: purefa2.lab.local
    mssql:
      hosts:
        eqx-sqlserver:
          ansible_host: 172.27.136.229
          

