---
- name: set purefa2 volume serial number
  set_fact:
    purefa2_vol_serial: "{{ hostvars['purefa2']['purefa2_vol_serial'] }}"
  run_once: True

- name: Gather Facts
  win_disk_facts:

- name: Query for Individual Purefa2 Disk
  #hosts: winsrv02.lab.local
  set_fact:
    pure_disk_info: "{{ (ansible_disks | json_query(query))[0] }}"
  vars:
    query: "[?physical_disk.serial_number=='{{purefa2_vol_serial}}']"

#- name: offline disk
#  win_shell: !unsafe |
#    Set-Disk -Number "{{ pure_disk_info.number }}" -IsOffline $True

- name: online disk
  win_shell: !unsafe |
    "Set-Disk -Number {{ pure_disk_info.number }} -IsOffline ${{ state }}"