---
- name: manage pure replication
  hosts: purefa
  gather_facts: False
  tasks:
    - name: populate API keys for each pure module
      set_fact:
        pure_credentials: &pure_api_info
          fa_url: "{{ ansible_host }}"
          api_token: "{{ purefa_api_token }}"
      tags:
        - configuration
        - snapshot
        - test

    - name: connect arrays for syncing
      delegate_to: localhost
      purestorage.flasharray.purefa_connect:
        target_url: "{{ hostvars['purefa2']['ansible_host'] }}"
        target_api: "{{ hostvars['purefa2']['purefa_api_token'] }}"
        connection: async
        <<: *pure_api_info
      run_once: True
      tags:
        - configuration

    - name: ensure protection groups are created
      delegate_to: localhost
      purestorage.flasharray.purefa_pg:
        pgroup: "{{ item.value.volume_name }}-PG"
        <<: *pure_api_info
      loop: "{{ volumes | dict2items }}"
      tags:
        - configuration

    - name: create list of volumes to add to protection group
      set_fact:
        volume_list: "{{ volumes | map(attribute='volume_name') | list }}"
      tags:
        - configuration

    - name: configure protection group to have a target array
      delegate_to: localhost
      purestorage.flasharray.purefa_pg:
        volume: 
          - "{{ item.value.volume_name }}"
        pgroup: "{{ item.value.volume_name }}-PG"
        target: 'purefa2'
        state: present
        eradicate: True
        <<: *pure_api_info
      when: inventory_hostname == source_array
      loop: "{{ volumes | dict2items }}"
      tags:
        - replication

    - name: add volume(s) to protection group on target_array
      delegate_to: localhost
      purestorage.flasharray.purefa_pg:
        volume: 
          - "{{ item.value.volume_name }}"
        pgroup: "{{ item.value.volume_name }}-PG"
        #target: 'purefa2'
        <<: *pure_api_info
      loop: "{{ volumes | dict2items }}"
      when: inventory_hostname == target_array
      tags:
        - configuration

    - name: set fact for which database to restore
      # there are 5 databases that can be referenced by db1, db2, db3, db4, or db5
      set_fact:
        db_choice: "{{ db_choice | default(default_db) }}"
      tags:
        - snapshot
    
    - name: create pg suffix
      delegate_to: localhost
      set_fact: 
        pg_suffix: "SNAP{{ 101 | random }}"
      run_once: True
      tags:
        - snapshot

    - name: create pg snapshot and replicate to other array
      delegate_to: localhost
      purestorage.flasharray.purefa_pgsnap:
        #name: "{{ pg_name | default(default_pg_name) }}"
        name: "{{ item.value.volume_name }}-PG"
        suffix: "{{ pg_suffix }}"
        remote: True
        now: True
        <<: *pure_api_info
      run_once: True
      when: item.key == db_choice
      loop: "{{ volumes | dict2items }}"
      tags:
        - snapshot
    
    - name: print name of created snapshot
      debug:
        msg: "Created Snapshot: {{ item.value.volume_name }}-PG.{{ pg_suffix }}"
      when: item.key == db_choice
      loop: "{{ volumes | dict2items }}"
      run_once: True

      tags: 
        - snapshot

    - name: pause to let replication occur
      pause:
        seconds: 20
      run_once: True
      tags:
        - snapshot

    - name: copy snapshot to target volume
      delegate_to: localhost
      purestorage.flasharray.purefa_pgsnap:
        name: "purefa1:{{ item.value.volume_name }}-PG"
        suffix: "{{ pg_suffix }}"
        restore: "{{ item.value.volume_name }}"
        #restore: sqlserver2019-db1
        overwrite: True
        state: copy
        <<: *pure_api_info
      when: inventory_hostname == 'purefa2' and item.key == db_choice
      loop: "{{ volumes | dict2items }}"
      tags:
        - snapshot
        - test
      

