- name: reset mongodb
  hosts: winsrv
  gather_facts: false

  tasks:
    - name: install pymongo
      win_command: powershell.exe -
      args:
        stdin: C:\python\python -m pip install pymongo

    - name: run python script to reset mongodb
      win_command: powershell.exe -
      args:
        chdir: C:\
        stdin: C:\python\python mongo-delete.py

    - name: stop mongodb service
      ansible.windows.win_service:
        name: MongoDB
        state: stopped
