---
- name: create a new volume
  hosts: purefa
  gather_facts: False
  tasks:

    - name: set fact for which database to restore
      # there are 5 databases that can be referenced by db1, db2, db3, db4, or db5
      set_fact:
        db_choice: "{{ db_choice | default(default_db) }}"

    - name: set fact for which volume to mount to windows
      set_fact:
        win_volume_name: "{{ item.value.volume_name }}"
      when: item.key == db_choice
      loop: "{{ volumes | dict2items }}"

    - name: include pause role
      include_role:
        name: diskinfo
      vars: 
        db_choice: db_choice
        win_volume_name: win_volume_name