---
- name: create a new volume
  hosts: purefa2
  gather_facts: False
  tasks:
    - name: create new volume
      delegate_to: localhost
      purestorage.flasharray.purefa_volume:
        fa_url: purefa2.lab.local
        api_token: a71006c9-3270-3540-04d4-58f80748266b
        name: I-created-a-volume-with-ansible
        size: 1T
        state: present
