---
- name: create a new banner
  hosts: purefa1
  gather_facts: False
  vars:
    banner_text:  "WWT Pure Automation Lab: \n Managed by Ansible!"

  tasks:
    - name: Set new banner text
      delegate_to: localhost
      purestorage.flasharray.purefa_banner:
        banner: "{{ banner_text }}"
        state: present
        fa_url: purefa1.lab.local
        api_token: 125cfec6-560a-ca26-e7af-27be411d3959