---
- name: create multiple volumes on multiple arrays
  hosts: purefa
  gather_facts: False
  tasks:
    - name: create new volume(s)
      delegate_to: localhost
      purestorage.flasharray.purefa_volume:
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ purefa_api_token }}"
        name: "{{ item.volume_name }}"
        size: "{{ item.volume_size }}"
        state: present
      loop: "{{ volumes }}"

    - name: ensure protection groups are created
      delegate_to: localhost
      purestorage.flasharray.purefa_pg:
        fa_url: "{{ inventory_hostname }}"
        api_token: "{{ purefa_api_token }}"
        pgroup: "{{ item.volume_name }}-PG"
      loop: "{{ volumes }}"
