---
- name: create multiple volumes on multiple arrays
  hosts: purefa
  gather_facts: False

  vars:
    banner_text:  "WWT Pure Automation Lab: \n Managed by Ansible!"
    pure_credentials: &pure_api_info
      fa_url: "{{ ansible_host }}"
      api_token: "{{ purefa_api_token }}"

  tasks:
    - name: Set new banner text
      delegate_to: localhost
      purestorage.flasharray.purefa_banner:
        <<: *pure_api_info
        banner: "{{ banner_text }}"
        state: present

    - name: create new volume(s)
      delegate_to: localhost
      purestorage.flasharray.purefa_volume:
        <<: *pure_api_info
        name: "{{ item.volume_name }}"
        size: "{{ item.volume_size }}"
        state: present
      loop: "{{ volumes_dict_list }}"
