---
- name: create multiple volumes on multiple arrays
  hosts: purefa
  gather_facts: False
  tasks:
    - name: populate API keys for each pure module
      set_fact:
        pure_credentials: &pure_api_info
          fa_url: "{{ ansible_host }}"
          api_token: "{{ purefa_api_token }}"

    - name: create new volume(s)
      delegate_to: localhost
      purestorage.flasharray.purefa_volume:
        <<: *pure_api_info
        name: "{{ item.volume_name }}"
        size: "{{ item.volume_size }}"
        state: present
      loop: "{{ volumes }}"

    - name: ensure protection groups are created
      delegate_to: localhost
      purestorage.flasharray.purefa_pg:
        <<: *pure_api_info
        pgroup: "{{ item.volume_name }}-PG"
      loop: "{{ volumes }}"
