---
- name: create multiple volumes on multiple arrays
  hosts: purefa
  gather_facts: False

  tasks:
    - name: populate API keys for each pure module
      set_fact:
        pure_credentials: &pure_api_info
          fa_url: "{{ ansible_host }}"
          api_token: "{{ purefa_api_token }}"
        tags:
          - system
          - volumes

    - name: Set new banner text
      delegate_to: localhost
      purestorage.flasharray.purefa_banner:
        <<: *pure_api_info
        banner: "{{ banner_text }}"
        state: present
      tags: system

    - name: create new volume(s)
      delegate_to: localhost
      purestorage.flasharray.purefa_volume:
        <<: *pure_api_info
        name: "{{ item.value.volume_name }}"
        size: "{{ item.value.volume_size }}"
        state: "{{ item.value.vol_state | default('present') }}"
      loop: "{{ volumes | dict2items}}"
      tags: volumes
