---
- name: create replication
  hosts: purefa
  gather_facts: False
  tasks:
    - name: populate API keys for each pure module
      set_fact:
        pure_credentials: &pure_api_info
          fa_url: "{{ ansible_host }}"
          api_token: "{{ purefa_api_token }}"

    - name: connect arrays for syncing
      delegate_to: localhost
      purestorage.flasharray.purefa_connect:
        target_url: "{{ hostvars['purefa2']['ansible_host'] }}"
        target_api: "{{ hostvars['purefa2']['purefa_api_token'] }}"
        connection: async
        <<: *pure_api_info
      run_once: True

    - name: configure protection group to have a target array
      delegate_to: localhost
      purestorage.flasharray.purefa_pg:
        volume: 
          - "{{ item.value.volume_name }}"
        pgroup: "{{ item.value.volume_name }}-PG"
        target: 'purefa2'
        state: present
        eradicate: True
        <<: *pure_api_info
      when: inventory_hostname == source_array
      loop: "{{ volumes | dict2items }}"
      tags:
        - replication