---
- name: create a new volume
  hosts: purefa
  gather_facts: False
  tasks:

    - name: set fact for which database to restore
      # there are 5 databases that can be referenced by db1, db2, db3, db4, or db5
      set_fact:
        db_choice: "{{ db_choice | default(default_db) }}"

    - name: set fact for which volume to mount to windows
      set_fact:
        win_volume_name: "{{ item.value.volume_name }}"
      when: item.key == db_choice
      loop: "{{ volumes | dict2items }}"

    - name: include get disk info
      include_role:
        name: diskinfo
      vars: 
        db_choice: db_choice
        vol_name: "{{ win_volume_name }}"
        state: True

- name: create windows disks
  hosts: winsrv02.lab.local
  gather_facts: False
  tasks:
    - name: set winsrv02 disk to offline
      include_role:
        name: set_win_disks
      vars:
        state: "True"

    - name: set winsrv02 disk to online
      include_role:
        name: set_win_disks
      vars:
        state: "False"