---
purefa_api_token: a71006c9-3270-3540-04d4-58f80748266b

purefa_win_hosts_iscsi:
  winsrv02:
    iqn: iqn.1991-05.com.microsoft:winsrv02.lab.local

purefa_winsrv_host_group:
  winsrv02:
    - winsrv02