---
default_pg_name: sqlserver2019-db1-PG
default_target_volume: sqlserver2019-db1
default_db: db1

volumes:
  - volume_name: Mongo-db1
    volume_size: 200G
  - volume_name: Mongo-db2
    volume_size: 200G
  - volume_name: Mongo-db3
    volume_size: 200G
  - volume_name: Mongo-db4
    volume_size: 200G
  - volume_name: Mongo-db5
    volume_size: 2T
  - volume_name: Replication_Demo
    volume_size: 100G
